config/routes.rb
Rails.application.routes.draw do

  root to: 'page#homepage'

  resources :oudoor_units
  resources :indoor_units
  resources :point_details
  resources :points
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/point_detail.rb
class PointDetail < ApplicationRecord
  belongs_to :point
end

app/controllers/point_details_controller.rb
class PointDetailsController < ApplicationController
  before_action :set_point_detail, only: %i[ show edit update destroy ]

  # GET /point_details or /point_details.json
  def index
    @point_details = PointDetail.all
  end

  # GET /point_details/1 or /point_details/1.json
  def show
  end

  # GET /point_details/new
  def new
    @point_detail = PointDetail.new
  end

  # GET /point_details/1/edit
  def edit
  end

  # POST /point_details or /point_details.json
  def create
    @point_detail = PointDetail.new(point_detail_params)

    respond_to do |format|
      if @point_detail.save
        format.html { redirect_to @point_detail, notice: "Point detail was successfully created." }
        format.json { render :show, status: :created, location: @point_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @point_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /point_details/1 or /point_details/1.json
  def update
    respond_to do |format|
      if @point_detail.update(point_detail_params)
        format.html { redirect_to @point_detail, notice: "Point detail was successfully updated." }
        format.json { render :show, status: :ok, location: @point_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @point_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /point_details/1 or /point_details/1.json
  def destroy
    @point_detail.destroy
    respond_to do |format|
      format.html { redirect_to point_details_url, notice: "Point detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_point_detail
      @point_detail = PointDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def point_detail_params
      params.require(:point_detail).permit(:point_id, :image, :title)
    end
end

app/helpers/point_details_helper.rb
module PointDetailsHelper
end

app/views/point_details/_form.html.erb
<%= form_with(model: point_detail, local: true) do |form| %>
  <% if point_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(point_detail.errors.count, "error") %> prohibited this point_detail from being saved:</h2>

      <ul>
      <% point_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :point_id %>
    <%= form.text_field :point_id %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/point_details/edit.html.erb
<h1>Editing Point Detail</h1>

<%= render 'form', point_detail: @point_detail %>

<%= link_to 'Show', @point_detail %> |
<%= link_to 'Back', point_details_path %>

app/views/point_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Point Details</h1>

<table>
  <thead>
    <tr>
      <th>Point</th>
      <th>Image</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @point_details.each do |point_detail| %>
      <tr>
        <td><%= point_detail.point %></td>
        <td><%= point_detail.image %></td>
        <td><%= point_detail.title %></td>
        <td><%= link_to 'Show', point_detail %></td>
        <td><%= link_to 'Edit', edit_point_detail_path(point_detail) %></td>
        <td><%= link_to 'Destroy', point_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Point Detail', new_point_detail_path %>

app/views/point_details/new.html.erb
<h1>New Point Detail</h1>

<%= render 'form', point_detail: @point_detail %>

<%= link_to 'Back', point_details_path %>

app/views/point_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Point:</strong>
  <%= @point_detail.point %>
</p>

<p>
  <strong>Image:</strong>
  <%= @point_detail.image %>
</p>

<p>
  <strong>Title:</strong>
  <%= @point_detail.title %>
</p>

<%= link_to 'Edit', edit_point_detail_path(@point_detail) %> |
<%= link_to 'Back', point_details_path %>