config/routes.rb
Rails.application.routes.draw do

  root to: 'page#homepage'

  resources :oudoor_units
  resources :indoor_units
  resources :point_details
  resources :points
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/indoor_unit.rb
class IndoorUnit < ApplicationRecord
end

app/controllers/indoor_units_controller.rb
class IndoorUnitsController < ApplicationController
  before_action :set_indoor_unit, only: %i[ show edit update destroy ]

  # GET /indoor_units or /indoor_units.json
  def index
    @indoor_units = IndoorUnit.all
  end

  # GET /indoor_units/1 or /indoor_units/1.json
  def show
  end

  # GET /indoor_units/new
  def new
    @indoor_unit = IndoorUnit.new
  end

  # GET /indoor_units/1/edit
  def edit
  end

  # POST /indoor_units or /indoor_units.json
  def create
    @indoor_unit = IndoorUnit.new(indoor_unit_params)

    respond_to do |format|
      if @indoor_unit.save
        format.html { redirect_to @indoor_unit, notice: "Indoor unit was successfully created." }
        format.json { render :show, status: :created, location: @indoor_unit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @indoor_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /indoor_units/1 or /indoor_units/1.json
  def update
    respond_to do |format|
      if @indoor_unit.update(indoor_unit_params)
        format.html { redirect_to @indoor_unit, notice: "Indoor unit was successfully updated." }
        format.json { render :show, status: :ok, location: @indoor_unit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @indoor_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indoor_units/1 or /indoor_units/1.json
  def destroy
    @indoor_unit.destroy
    respond_to do |format|
      format.html { redirect_to indoor_units_url, notice: "Indoor unit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_indoor_unit
      @indoor_unit = IndoorUnit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def indoor_unit_params
      params.require(:indoor_unit).permit(:title, :point)
    end
end

app/helpers/indoor_units_helper.rb
module IndoorUnitsHelper
end

app/views/indoor_units/_form.html.erb
<%= form_with(model: indoor_unit, local: true) do |form| %>
  <% if indoor_unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(indoor_unit.errors.count, "error") %> prohibited this indoor_unit from being saved:</h2>

      <ul>
      <% indoor_unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :point %>
    <%= form.text_field :point %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/indoor_units/edit.html.erb
<h1>Editing Indoor Unit</h1>

<%= render 'form', indoor_unit: @indoor_unit %>

<%= link_to 'Show', @indoor_unit %> |
<%= link_to 'Back', indoor_units_path %>

app/views/indoor_units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Indoor Units</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Point</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @indoor_units.each do |indoor_unit| %>
      <tr>
        <td><%= indoor_unit.title %></td>
        <td><%= indoor_unit.point %></td>
        <td><%= link_to 'Show', indoor_unit %></td>
        <td><%= link_to 'Edit', edit_indoor_unit_path(indoor_unit) %></td>
        <td><%= link_to 'Destroy', indoor_unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Indoor Unit', new_indoor_unit_path %>

app/views/indoor_units/new.html.erb
<h1>New Indoor Unit</h1>

<%= render 'form', indoor_unit: @indoor_unit %>

<%= link_to 'Back', indoor_units_path %>

app/views/indoor_units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @indoor_unit.title %>
</p>

<p>
  <strong>Point:</strong>
  <%= @indoor_unit.point %>
</p>

<%= link_to 'Edit', edit_indoor_unit_path(@indoor_unit) %> |
<%= link_to 'Back', indoor_units_path %>