config/routes.rb
Rails.application.routes.draw do

  root to: 'page#homepage'

  resources :oudoor_units
  resources :indoor_units
  resources :point_details
  resources :points
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/oudoor_unit.rb
class OudoorUnit < ApplicationRecord
end

app/controllers/oudoor_units_controller.rb
class OudoorUnitsController < ApplicationController
  before_action :set_oudoor_unit, only: %i[ show edit update destroy ]

  # GET /oudoor_units or /oudoor_units.json
  def index
    @oudoor_units = OudoorUnit.all
  end

  # GET /oudoor_units/1 or /oudoor_units/1.json
  def show
  end

  # GET /oudoor_units/new
  def new
    @oudoor_unit = OudoorUnit.new
  end

  # GET /oudoor_units/1/edit
  def edit
  end

  # POST /oudoor_units or /oudoor_units.json
  def create
    @oudoor_unit = OudoorUnit.new(oudoor_unit_params)

    respond_to do |format|
      if @oudoor_unit.save
        format.html { redirect_to @oudoor_unit, notice: "Oudoor unit was successfully created." }
        format.json { render :show, status: :created, location: @oudoor_unit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @oudoor_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oudoor_units/1 or /oudoor_units/1.json
  def update
    respond_to do |format|
      if @oudoor_unit.update(oudoor_unit_params)
        format.html { redirect_to @oudoor_unit, notice: "Oudoor unit was successfully updated." }
        format.json { render :show, status: :ok, location: @oudoor_unit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @oudoor_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oudoor_units/1 or /oudoor_units/1.json
  def destroy
    @oudoor_unit.destroy
    respond_to do |format|
      format.html { redirect_to oudoor_units_url, notice: "Oudoor unit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oudoor_unit
      @oudoor_unit = OudoorUnit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def oudoor_unit_params
      params.require(:oudoor_unit).permit(:title, :point)
    end
end

app/helpers/oudoor_units_helper.rb
module OudoorUnitsHelper
end

app/views/oudoor_units/_form.html.erb
<%= form_with(model: oudoor_unit, local: true) do |form| %>
  <% if oudoor_unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(oudoor_unit.errors.count, "error") %> prohibited this oudoor_unit from being saved:</h2>

      <ul>
      <% oudoor_unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :point %>
    <%= form.text_field :point %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/oudoor_units/edit.html.erb
<h1>Editing Oudoor Unit</h1>

<%= render 'form', oudoor_unit: @oudoor_unit %>

<%= link_to 'Show', @oudoor_unit %> |
<%= link_to 'Back', oudoor_units_path %>

app/views/oudoor_units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Oudoor Units</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Point</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @oudoor_units.each do |oudoor_unit| %>
      <tr>
        <td><%= oudoor_unit.title %></td>
        <td><%= oudoor_unit.point %></td>
        <td><%= link_to 'Show', oudoor_unit %></td>
        <td><%= link_to 'Edit', edit_oudoor_unit_path(oudoor_unit) %></td>
        <td><%= link_to 'Destroy', oudoor_unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Oudoor Unit', new_oudoor_unit_path %>

app/views/oudoor_units/new.html.erb
<h1>New Oudoor Unit</h1>

<%= render 'form', oudoor_unit: @oudoor_unit %>

<%= link_to 'Back', oudoor_units_path %>

app/views/oudoor_units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @oudoor_unit.title %>
</p>

<p>
  <strong>Point:</strong>
  <%= @oudoor_unit.point %>
</p>

<%= link_to 'Edit', edit_oudoor_unit_path(@oudoor_unit) %> |
<%= link_to 'Back', oudoor_units_path %>